#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "post-commit".



echo "Running the post commit hook..."

GIT_DIR_="$(git rev-parse --git-dir)"


if [ -f $GIT_DIR_/isToUpdateTheGalileoFile.txt ]
then
    echo "Applying git reset to VERSION.txt and scripting/galileo.sma..."
    git reset VERSION.txt
    git reset scripting/galileo.sma
    rm $GIT_DIR_/isToUpdateTheGalileoFile.txt
else
    echo "It is not time to updated the 'galileo.sma' file."
fi



echo "Successfully executed the post commit hook."


