#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "post-commit".



echo "Running the post commit hook..."


echo "Applying git reset to VERSION.txt and scripting/include/galileo.inc..."
git reset VERSION.txt
git reset scripting/include/galileo.inc


echo "Successfully executed the post commit hook."


