#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".



GIT_DIR_="$(git rev-parse --git-dir)"


if sh $GIT_DIR_/../updateVersion.sh build; then
    echo "Successfully ran updateVersion.sh"
    exit 0
else
    echo "Could not update updateVersion.sh right!"
    exit 1
fi



