#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".



echo "Running the pre-commit hook..."


GIT_DIR_="$(git rev-parse --git-dir)"

currentVersion=$(git diff --name-only --cached)


# to clean any old missed file
if [ -f $GIT_DIR_/isToUpdateTheGalileoFile.txt ]
then
    rm $GIT_DIR_/isToUpdateTheGalileoFile.txt
fi


if [[ $currentVersion == *"galileo.sma"* ]]
then
    if sh $GIT_DIR_/../updateVersion.sh build
    then
        echo "isToUpdateTheGalileoFile" > $GIT_DIR_/isToUpdateTheGalileoFile.txt
        echo "Successfully ran updateVersion.sh"
    else
        echo "Could not update updateVersion.sh right!"
        exit 1
    fi
else
    echo "The 'galileo.sma' file is not being committed right now."
fi


echo "Successfully executed the pre-commit hook."
exit 0


