#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "post-commit".



echo "Running the post-commit hook..."


GIT_DIR_="$(git rev-parse --git-dir)"
updateVersionProgram=githooks/updateVersion.sh



# Updates and changes the files if the flag file exits.
if [ -f $GIT_DIR_/isToUpdateTheGalileoFile.txt ]
then
    sh $GIT_DIR_/../$updateVersionProgram build
    echo "Amending commits..."
    git commit --amend -C HEAD --no-verify
else
    echo "It is not time amend as the file 'isToUpdateTheGalileoFile.txt' does not exist."
fi


# To clean any old missed file
if [ -f $GIT_DIR_/isToUpdateTheGalileoFile.txt ]
then
    echo "Removing old post-commit configuration file 'isToUpdateTheGalileoFile.txt'..."
    rm $GIT_DIR_/isToUpdateTheGalileoFile.txt
fi


exit 0


