#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "post-commit".



echo "Running the post-commit hook..."


GIT_DIR_="$(git rev-parse --git-dir)"

versionFileName=githooks/GALILEO_VERSION.txt
fileToUpdate=scripting/galileo.sma


if [ -f $GIT_DIR_/isToUpdateTheGalileoFile.txt ]
then
    echo "Amending $versionFileName and $fileToUpdate..."
    git add $versionFileName
    git add $fileToUpdate
    git commit --amend
else
    echo "It is not time to update the $fileToUpdate file."
fi


# To clean any old missed file
if [ -f $GIT_DIR_/isToUpdateTheGalileoFile.txt ]
then
    rm $GIT_DIR_/isToUpdateTheGalileoFile.txt
fi


echo "Successfully executed the post-commit hook."
exit 0


